Первое ДЗ
apatamy4to/JAVA1 pull request #1
Opened 2019-10-10 22:09 UTC by apatamy4to

2019-10-11 04:35 UTC, apatamy4to reviewed
8 задание в процессе выполнения.
Логика мне ясна, необходимо построить метод основанный на сравнение.

2019-10-11 08:39 UTC, DisterDE requested changes
Стоит перенести все методы в один класс и вызывать их там в методе main.
Так же советую перед коммитом нажимать Ctrl + Alt + L, тогда идея стандартизирует пробелы, отступы и прочее.

2019-10-11 08:39 UTC, DisterRU commented on Task2.java
> +        boolean I = true;
Переменные не принято называть с большой буквы. Исключение: константы.

2019-10-11 08:39 UTC, DisterRU commented on Task3.java
> +        return result;
Зачем вводить переменную?
Можно просто написать `return a * (b + (c / d));`

2019-10-11 08:39 UTC, DisterRU commented on Task4.java
> +import java.security.spec.RSAOtherPrimeInfo;
Стоит убрать.
Ctrl + Alt + O убирает незадействованные импорты.
Даже боюсь представить, как ты умудрился достучаться до класса с таким именем.

2019-10-11 08:39 UTC, DisterRU commented on Task4.java
> +        }
`return a + b >= 10 && a + b <= 20;`

2019-10-11 08:39 UTC, DisterRU commented on Task6.java
> +        }
`return a < 0;`

2019-10-11 08:39 UTC, DisterRU commented on Task7.java
> +        return result;
Опять же в чем смысл ввода лишней переменной?
`return "Привет " + name + " !";`

2019-10-12 06:06 UTC, apatamy4to commented on Task6.java
> +        }
При написание данного кода мой подход был мне более очевидным.

2019-10-12 06:07 UTC, apatamy4to commented on Task4.java
> +        }
При написание данного кода мой подход был мне более очевидным.

2019-10-12 06:08 UTC, apatamy4to commented on Task4.java
> +import java.security.spec.RSAOtherPrimeInfo;
Кривые пальцы творят чудеса.

2019-10-12 06:10 UTC, apatamy4to commented on Task3.java
> +        return result;
Переменную вводил для тренировки написания более сложных функций. В которых бы нельзя было написать код в одну строку.

2019-10-12 06:11 UTC, apatamy4to commented on Task2.java
> +        boolean I = true;
Исправлено

2019-10-12 06:11 UTC, merged